import React, { useState, useEffect, useMemo } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { FaArrowLeft, FaCheckCircle, FaPaperPlane } from "react-icons/fa";

const DoctorApprovalWindow = () => {

  const { patientID } = useParams();
  const navigate = useNavigate();
  const backendURL = useMemo(() => import.meta.env.VITE_BACKEND_URL, []);
  const authToken = useMemo(() => localStorage.getItem("token"), []);

  const [patient, setPatient] = useState(null);
  const [feedback, setFeedback] = useState("");
  const [loading, setLoading] = useState(true);

  // Fetching the data of the patient when the window opens.
  useEffect(() => {
    const fetchPatient = async () => {
      try {
        const response = await fetch(`${backendURL}/doctor/patient?patientID=${patientID}`, {
          headers: {
            Authorization: `Bearer ${authToken}`
           },
          method: "POST",
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.response);
        }

        setPatient(data);
      } catch (error) {
        toast.error(error.message);
      } finally {
        setLoading(false);
      }

    };

    fetchPatient();

  }, [patientID, backendURL, authToken]);

  // Handling approve if the doctor is satisfied with the data that
  // was generated by the System.
  const handleApprove = async () => {
    try {

      const response = await fetch(`${backendURL}/doctor/approve?patientID=${patientID}`, {
        method: "GET", // Sending GET request although we just need to check for apporval.
        headers: {
          Authorization: `Bearer ${authToken}`,
        }
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.response);
      }

      toast.success(data.response);

      navigate("/dashboard/doctor");

    } catch (error) {
      toast.error(error.message);
    }
  };

  // This function will handle the sending and approving of the consultation.
  const handleSendFeedback = async () => {
    try {

      const response = await fetch(`${backendURL}/doctor/feedback`, {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${authToken}`,
        },
        body: JSON.stringify({
          "patientID": patientID,
          "feedback": feedback,
        }),
        method: "POST",
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.response);
      }

      toast.success(data.response);

      // Since we have done the feedback part just need to go back.
      navigate("/dashboard/doctor")

    } catch (error) {
      toast.error(error.message);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[80vh] text-gray-600">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-green-600 mb-3"></div>
        <p>Loading patient details...</p>
      </div>
    );
  }

  if (!patient) {
    return (
      <div className="text-center mt-20 text-gray-600">
        <p>No patient data found.</p>
        <button
          className="mt-4 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
          onClick={() => navigate("/doctor/dashboard")}
        >
          Go Back
        </button>
      </div>
    );
  }

  const { assessment } = patient;

  return (
    <div className="w-full min-h-screen bg-gradient-to-br from-green-50 via-white to-green-100 p-4 sm:p-8">
      <div className="max-w-5xl mx-auto bg-white rounded-2xl shadow-lg p-6 sm:p-10">

        <button
          className="flex items-center gap-2 text-gray-600 hover:text-green-700 mb-6"
          onClick={() => navigate("/dashboard/doctor")}
        >
          <FaArrowLeft /> Back to Dashboard
        </button>

        <h1 className="text-2xl sm:text-3xl font-bold text-gray-800 mb-6">
          Consultation Review — {patient.name}
        </h1>

        <div className="bg-green-50 p-4 rounded-xl mb-6 border border-green-100 text-sm sm:text-base">
          <p><span className="font-semibold">Patient ID:</span> {patient.id}</p>
          <p><span className="font-semibold">Age:</span> {patient.age}</p>
          <p><span className="font-semibold">Gender:</span> {patient.gender}</p>
          <p><span className="font-semibold">Height:</span> {patient.height}</p>
          <p><span className="font-semibold">Weight:</span> {patient.weight}</p>
          <p><span className="font-semibold">Height:</span> {patient.height}</p>
        </div>

        {/* Ayurveda Sections */}
        <div className="grid gap-4 mb-6">
          {assessment?.basicAssessment && (
            <div className="bg-green-50 p-4 rounded-xl">
              <h3 className="text-lg font-semibold text-green-800 mb-2">Basic Assessment</h3>
              <p>Activity Level: {assessment.basicAssessment.activityLevel}</p>
              <p>Meal Frequency: {assessment.basicAssessment.mealFrequency}</p>
              <p>Water Intake: {assessment.basicAssessment.waterIntake} L/day</p>
              <p>Sleeping Schedule: {assessment.basicAssessment.sleepingSchedule}</p>
              <p>Hours of Sleep: {assessment.basicAssessment.hoursOfSleep}</p>
              <p>Preferred Food Genre: {assessment.basicAssessment.preferredFoodGenre}</p>
            </div>
          )}

          {assessment?.healthAssessment && (
            <div className="bg-green-50 p-4 rounded-xl">
              <h3 className="text-lg font-semibold text-green-800 mb-2">Health Assessment</h3>
              <p>Agni: {assessment.healthAssessment.agni}</p>
              <p>Health Issues: {assessment.healthAssessment.healthIssues?.join(", ")}</p>
              <p>Allergies: {assessment.healthAssessment.allergies?.join(", ")}</p>
              <p>Preferred Tastes: {assessment.healthAssessment.preferredTastes?.join(", ")}</p>
            </div>
          )}

          {assessment?.prakrutiAssessment && (
            <div className="bg-green-50 p-4 rounded-xl">
              <h3 className="text-lg font-semibold text-green-800 mb-2">Prakruti Assessment</h3>
              <p>Body Type: {assessment.prakrutiAssessment.bodyType}</p>
              <p>Skin Nature: {assessment.prakrutiAssessment.skinNature}</p>
              <p>Digestion Strength: {assessment.prakrutiAssessment.digestionStrength}</p>
              <p>Energy Pattern: {assessment.prakrutiAssessment.energyPattern}</p>
              <p>Sleep Nature: {assessment.prakrutiAssessment.sleepNature}</p>
            </div>
          )}

          {assessment?.vikrutiAssessment && (
            <div className="bg-green-50 p-4 rounded-xl">
              <h3 className="text-lg font-semibold text-green-800 mb-2">Vikruti Assessment</h3>
              <p>Current Concerns: {assessment.vikrutiAssessment.currentConcerns}</p>
              <p>Current Energy: {assessment.vikrutiAssessment.currentEnergy}</p>
              <p>Current Sleep: {assessment.vikrutiAssessment.currentSleep}</p>
              <p>Digestion Today: {assessment.vikrutiAssessment.digestionToday}</p>
            </div>
          )}
        </div>

        {/* Calculated Ayurveda Details */}
        <div className="bg-green-100 p-4 rounded-xl mb-6">
          <h3 className="text-lg font-semibold text-green-900 mb-2">Calculated Ayurvedic Insights</h3>
          <p><strong>Prakruti:</strong> {patient.prakruti}</p>
          <p><strong>Vikruti:</strong> {patient.vikruti}</p>
        </div>

        {/* Doctor Feedback Input */}
        <label className="block text-gray-800 font-medium mb-2">
          Doctor's Feedback / Prescription
        </label>
        <textarea
          rows="6"
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          placeholder="Write your diagnosis, suggestions, or prescriptions here..."
          className="w-full border border-gray-300 rounded-xl p-4 focus:ring-2 focus:ring-green-500 focus:outline-none mb-6"
        ></textarea>

        <div className="flex flex-col sm:flex-row gap-4">

          {/* If the doctor wants some improvement they can send the feedback
          the feedback will be saved to the patient database. */}
          <button
            onClick={handleSendFeedback}
            className="flex items-center justify-center gap-2 bg-blue-500 hover:bg-blue-600 text-white px-5 py-3 rounded-xl shadow transition"
          >
            <FaPaperPlane /> Send Feedback & Approve Consultation
          </button>

          {/* If the data that was calculated was OK and the doctor don't need
          any improvement he can directly approve too. */}
          <button
            onClick={handleApprove}
            className="flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-3 rounded-xl shadow transition"
          >
            <FaCheckCircle /> Approve Consultation
          </button>

        </div>
      </div>
    </div>
  );
};

export default DoctorApprovalWindow;
